### PR TITLE
Use Ivy for dependency management

### PR DESCRIPTION
**Pull request by eprenamer**
The basic idea here is that for most of our libraries, instead of having them checked into source code, we'd download them from the Maven central repository.  Because the **SWT** library is platform-dependent (and because the version we're using isn't in the central repository), for now it remains as checked-in "source code".  The **jEdit** library is not a standalone package, so it's still checked in, too.  All the other libraries will now be downloaded.

There is a little complication, because it's traditional and easiest to use the top-level _lib_ directory for downloading, and that's where the libraries had been checked in as source code.  This PR moves the SWT libraries from _lib_ into the _jars/main_ directory.  (This PR contains several methodical commits, and initially all the libraries were moved into the _jars_ directory, but as I integrated them with Ivy, I removed them from _jars_.)  Now _lib_ is known to Git as an "ignore" file, and that's where Ivy will put its downloads.

Note, Ivy runs automatically.  It is part of the build as the `resolve` task, and now `init` depends on `resolve`.  So, every time you build (or do pretty much anything else), Ivy will make sure your libraries are up to date.

The specifications in the Ivy file I'm committing specify exact versions.  So, Ivy will never "update" the libraries, unless/until we explicitly tell it so.  And once the right versions are downloaded, the Ivy check is very fast.

The only irritation is that Ivy produces kind of a lot of output.  I think that's ok.  If it becomes too annoying, someone can create an issue and I can look into ways of having it quiet down.

This also upgrades the version of **XStream**, because the version we were using was not available.  This version requires an additional dependency, **xmlpull**.  Ivy downloads both, and it works just the same.  I'm also updating the license text regarding XStream in the LICENSE file.  I've been working with this "new" version for a while and haven't seen any behavioral differences.

For the other libraries (**commons-codec**, **xpp**, **junit**, **mockito**), the versions are the same as what we've been using.

The Ivy file also downloads jars for checkstyle and findbugs.

This resolves the issue described in #116 , even if it doesn't use the method ("convert to Maven") that was suggested.

### CODE REVIEW

**Comment by eprenamer** [comment]
I think it's clear this test failed due to the site being down again, especially since the particular commit it failed on was nothing more than updating the LICENSE file.  :)  Is there a way I can tell the Travis tests to run again?

**Comment by daveharris** [comment]
I can do it but I *think* that's because TravisCI authenticates against GitHub and I'm a 'contributor' to the tvrenamer project.
We'll make you a contributor given your huge input this week!

The [build failed but with a seemingly legitimate error](https://travis-ci.org/tvrenamer/tvrenamer/builds/220866127)
```
build.xml:70: /home/travis/build/tvrenamer/tvrenamer/lib does not exist.
```

**Comment by eprenamer** [comment]
Ah, right.  OK, well that is definitely related.  :)  So, the automated build will need to call "ant resolve" before calling "ant test".  As I discussed in the OP, I didn't think it made sense to call "ant resolve" every time you run "ant compile", because it really only needs to be run once.

But it might be the simplest thing to just call "ant resolve" every time.  As I mentioned, it is pretty fast.  The only irritating part is the output  I could try redirecting it to /dev/null, or maybe nobody cares about the extra output.  :)

**Comment by eprenamer** [comment]
OK, changed it and rewrote the OP so that Ivy runs each time.

**Comment by eprenamer** [comment]
OK, another legitimate failure.  I forgot that when I installed Ivy long ago, I did copy its jar file into my ant/lib directory.  That's why it works, for me.

The error message is very helpful.  It suggests that this will work if the Ivy jar is copied into one of these locations:
~/usr/share/ant/lib
~/home/travis/.ant/lib

Offhand I don't know anything about setting this up.  Do either of you know if it's easy to do?

**Comment by vipuldelwadia** [comment]
Sounds like you need to run `ant` twice before running the actual build? Have a look at http://ecmendenhall.github.io/blog/blog/2013/05/28/two-travis-ci-solutions/

**Comment by eprenamer** [comment]
So is the idea to use ant to ensure that Ivy is installed?  What if ant is not installed?  There obviously is an idea of a "minimal system", and I think it would be better if it were simply that Ivy were required as part of that minimal system.

**Comment by eprenamer** [comment]
Do you guys think this is a good idea?  I kind of pushed it to the front just because I saw that #116 had been marked for this release.  But if you're hesitant about it (either because it's not Maven, or for any other reason) I'm happy to hold off.

**Comment by vipuldelwadia** [comment]
I'm not sure to be honest. You've done a bit of work to put in Ivy, which I appreciate, however I'm not sure what benefit we get from using it.

I would rather switch to something like Gradle, which has a much nicer build file syntax and handles things like incremental building, and is much better supported by CI systems like Travis CI.

@daveharris what are your thoughts?

**Comment by eprenamer** [comment]
I guess the primary benefit is just to not have large binary files checked in as source code.  Or, in this case, to have _fewer_ such files checked in.  It makes things easier if you want to upgrade a version (for example, we're using a pretty old version of jUnit, I think).

Perhaps what I'd suggest is to take the commit that moves the files from "lib" into "jars" (or some other directory, if you don't like the name "jars"), to make "lib" available as the non-source-code directory that Java developers and Java tools expect it to be.  And it would allow me to more easily use the Ivy configuration in my own branch, and be more straightforward to convert to gradle or anything else in the future.

**Comment by daveharris** [comment]
Let me first off say that I really appreciate the work you've done and you have certainly cleaned things up a lot which is fantastic. However, I'm torn like @vipuldelwadia...

My biggest issues I have with the current (before this PR) implementation are:
1. Binary jars are checked into the git which is bad practice and slow etc. I guess we could use Git LFS but that does seem a bit silly given that those things are source code, not images etc. Also we'd then need to add the LFS git extension to all of our clients and TravisCi
1. Updating the SWT version is **really annoying**. It's lots of downloading zip files, moving and renaming files. Therefore we don't do it very often.

So comparing against those 'acceptance criteria', this PR:
1. Somewhat solves the issue, however we still have a lot of jars checked in (I don't care what folder they are in). These are for legitimate reasons but the fact still remains. Didn't someone find some older SWT jars in Maven somewhere a few weeks ago? There's been so many issues/PRs it's hard to keep track!!!!
1. Doesn't help updating SWT (given that we SWT is our most updated library)

However, is something better than nothing? I feel like we are getting into the issue of "Perfect is the enemy of good".

I don't really mind if we merge this or not. If doing this makes it easier in the future to move to Gradle than maybe we should do it. Gradle isn't yet a full replacement of ant, but will it ever be? How far off will that be? I also don't really want to just throw away all your work and time!

This comment wasn't helpful *at all* 🤦‍♂️

**Comment by eprenamer** [comment]
Honestly, it's ok with me.  I thought you all wanted this change.  If you don't, it's not a problem.  At least for now.

As I'm sure you know, git never makes you throw away your work.  And, as this was purely a development issue, clearly the only benefit is to developers.  I will continue to get the benefits that I see, by keeping the changes live in un-pushed branches :-)

Given that you say you appreciate my work, I guess I'd like it if you'd accept the "nolib" change, even if you think it's utterly pointless.  It just will help me in my development to have the "lib" directory out of the way.  If you don't like the "jars" name, obviously I'd be happy to change that.

**Comment by eprenamer** [comment]
Thanks for taking "nolib"!  I had a thought, which seems kind of obvious in retrospect.  Can you just take these changes into an "ivy" branch in your repository?  This way it's available and obvious to anyone else who may want to work on the project, until we get a better Maven/Gradle solution.

**Comment by vipuldelwadia** [comment]
Yep that's a great idea.

I've tried to make you a collaborator on this project so that you have write access and can make the branches (and trigger builds on Travis) but I think your invite is still pending - if you accept that invite then you should be able to make the `ivy` branch and carry on from there.

**Comment by eprenamer** [comment]
Ah, ok, great!  I don't see it anywhere obvious, though.  Can you tell me where to go to see this pending invite and accept it?

**Comment by vipuldelwadia** [comment]
Perhaps https://github.com/tvrenamer/tvrenamer/invitations ?

**Comment by eprenamer** [comment]
Got it, thanks!

**Comment by eprenamer** [comment]
I pulled the changes into the ivy branch using the command line.

**Pull request closed without merging**
