### PR TITLE
Ignore options feature

### PR DESCRIPTION
**Pull request by ajdaniel**
A new feature to allow the user to supply terms to TVRenamer, which are compared against filenames when added to the list, and should any match, the file will be unchecked automatically. Useful to automatically ignore certain file types, such as .nfo, or additional files usually found accompanying TV shows, like samples.

### CODE REVIEW

**Comment by ajdaniel** [comment]
@vipuldelwadia or @daveharris I'd rather one of you guys accept this merge please. I don't want to do it and screw up :smile:

**Comment by ajdaniel** [comment]
Oh cool Github put the new commit into my merge request. @davekeane if you are happy with that could you accept the merge request please?

**Comment by davekeane** [comment]
Everything I've seen is good, but unfortunately I don't have a working dev environment to pull/test/review in. So I'm not comfortable clicking the merge button....

**Comment by vipuldelwadia** [comment]
Tested locally, looks good, nice work!

**Pull request merged**
